Traceback (most recent call last):
  File "spozberry.py", line 129, in <module>
    play_random_playlist(playlistList)
  File "spozberry.py", line 84, in play_random_playlist
    randomise_by_album(client) # Shuffle but keep albums together
  File "spozberry.py", line 11, in randomise_by_album
    currentPlaylist = client.playlistinfo()
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 629, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "spozberry.py", line 31, in randomise_by_album
    client.add(song["file"])
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 629, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 254, in _execute
    return retval()
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 623, in decorator
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 381, in _fetch_nothing
    raise ProtocolError("Got unexpected return value: '%s'" % line)
mpd.ProtocolError: Got unexpected return value: ': 2016'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "spozberry.py", line 47, in wait_for_input
    play_random_playlist(playlistList)
  File "spozberry.py", line 84, in play_random_playlist
    randomise_by_album(client) # Shuffle but keep albums together
  File "spozberry.py", line 32, in randomise_by_album
    except ProtocolError:
NameError: name 'ProtocolError' is not defined

  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 254, in _execute
    return retval()
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 623, in decorator
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 422, in _fetch_songs
    return self._fetch_objects(["file"])
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 410, in _fetch_objects
    return self._wrap_iterator(self._read_objects(delimiters))
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 374, in _wrap_iterator
    return list(iterator)
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 332, in _read_objects
    for key, value in self._read_pairs():
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 314, in _read_pairs
    pair = self._read_pair(separator)
  File "/usr/local/lib/python3.6/site-packages/mpd.py", line 307, in _read_pair
    raise ProtocolError("Could not parse pair: '%s'" % line)
mpd.ProtocolError: Could not parse pair: 'Datepotify:track:0hR7du7cwc4OukmbiCq2ZB'




/////// COMMENTS ////////

This is really fucked up because on line 22, _fetch_nothing() fetches the string ": 2016"
and then on line 55, _read_pair() fetches the string "Datepotify:track:0hR7du7cwc4OukmbiCq2ZB".
It looks like the line22string and the line55string are both a part of the same stringified
dictionary, with the pieces fitting together like so: "Date: 2016potify:track:0hR7du7cwc4OukmbiCq2ZB" 

So some of the stringified dictionary is lost, as seen by the lost 'S' in "potify:track:0hR7du7cwc4OukmbiCq2ZB"


Playing playlist $@Punctuation Triphop
spotify:track:4xv5yvrQObG1hMwogiTiJ0 Gathering of the Tribes
spotify:track:3chl0T6lusF7wqlO5dgMgk Forever Lost



